// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Encoder = require("./Encoder.bs.js");
var BrainJs = require("brain.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var YgoTextModel = require("ygo-text-model");

function rateText(sentence) {
  var net = new BrainJs.NeuralNetworkGPU();
  net.fromJSON(YgoTextModel);
  var splitByPunctuation = function (str) {
    return Belt_Array.keepMap(str.split(/[.!?,;:]/g), (function (str) {
                  return str;
                }));
  };
  var ratePhrase = function (input) {
    return BrainJs.likely(input, net);
  };
  var phrases = splitByPunctuation(sentence);
  return Belt_Array.map(Belt_Array.map(phrases, Encoder.encode), ratePhrase);
}

exports.rateText = rateText;
/* Encoder Not a pure module */
